name: flutter_geofire_plugin
description: A new flutter plugin project.
version: 0.0.1
author:
homepage:

flutter:
  plugin:
    androidPackage: com.vanbilsen.bram.flutter.geofire.fluttergeofireplugin
    pluginClass: FlutterGeofirePlugin

dependencies:
  flutter:
    sdk: flutter
